### ISSUE TITLE
live template

### ISSUE THREAD

**Issue by gustave001** [xiaoxiunique/awesome-IntelliJ-IDEA#11]
可以分享下自定义的live template吗，比如controller

**Comment by xiaoxiunique** [comment]
不好意思，以前确实整理过一些 Controller 的 live template， 不过现在我的工作方向 更多的在  Node.js 方向，所以现在主要的工具使用是 WebStorm ，而且以前也更多的配合的是 代码生成器 生成一些通用代码，如果有兴趣 我邮件发你一个生成器

**Comment by xiaoxiunique** [comment]
所以 这种 Live Template 用的不多

**Comment by kikyou93** [comment]
> 不好意思，以前确实整理过一些 Controller 的 live template， 不过现在我的工作方向 更多的在 Node.js 方向，所以现在主要的工具使用是 WebStorm ，而且以前也更多的配合的是 代码生成器 生成一些通用代码，如果有兴趣 我邮件发你一个生成器
好的啊，我邮箱1014016816@qq.com

**Comment by xiaoxiunique** [comment]
已发

**Comment by kikyou93** [comment]
> 已发

是发的1014016816@qq.com吗，我看了下没收到啊

**Comment by xiaoxiunique** [comment]
是的 就是这个邮箱。20号发的

**Comment by kikyou93** [comment]
> 是的 就是这个邮箱。20号发的

又去看了下，确实没收到，要不您再发一次？

**Comment by xiaoxiunique** [comment]
嗯嗯 发了 再看看 有没有没呢

**Comment by kikyou93** [comment]
嗯，收到了，谢谢
