### ISSUE TITLE
请教一个问题，请问图中按钮是否以及如何自定义呢？谢谢您的耐心指教。

### ISSUE THREAD

**Issue by LordHumphrey** [xiaoxiunique/awesome-IntelliJ-IDEA#3]
![image](https://user-images.githubusercontent.com/43847411/69591826-ed0fd800-102e-11ea-9f6d-da6b4a132afc.png)

**Comment by siwuxiesss** [comment]
自定义应该不可以，想改变样式的话可以去`settings---plugins`下载主题

**Comment by xiaoxiunique** [comment]
Setting | Appearance & Behavior | Menu and Toolbars | VCS Local Changes Toolbar 

选中你想要修改的 Action 点击 编辑，选择 Icon
