### ISSUE TITLE
请教一个问题，请问图中后缀模板能否以及如何自定义呢？

### ISSUE THREAD

**Issue by PlexPt** [xiaoxiunique/awesome-IntelliJ-IDEA#37]
![image](https://user-images.githubusercontent.com/15922823/127425336-e27371ee-39b9-4436-9ca6-224126641054.png)

![image](https://user-images.githubusercontent.com/15922823/127425389-efe2d384-d9ed-4899-97a7-6ee35e77739f.png)

默认的一些后缀

但是没找到自定义的地方，Live Template 里设置的好像没用

**Comment by xiaoxiunique** [comment]
在 Preferences / Editor / General / Postfix Completion 中定义

**Comment by xiaoxiunique** [comment]
> ![image](https://user-images.githubusercontent.com/15922823/127425336-e27371ee-39b9-4436-9ca6-224126641054.png)
> 
> ![image](https://user-images.githubusercontent.com/15922823/127425389-efe2d384-d9ed-4899-97a7-6ee35e77739f.png)
> 
> 默认的一些后缀
> 
> 但是没找到自定义的地方，Live Template 里设置的好像没用

在 Preferences / Editor / General / Postfix Completion 中定义
