### ISSUE TITLE
根据windows的快捷键怎么映射到mac下的？

### ISSUE THREAD

**Issue by yunjie-li** [xiaoxiunique/awesome-IntelliJ-IDEA#8]
![image](https://user-images.githubusercontent.com/15187773/78962668-67954c00-7b27-11ea-9fb9-4a874c399ea4.png)

文档中idea快捷键都是windows的，用mac无法知道是哪个快捷键，能否把快捷键前面的说明也写到文档上？这样就能找到相应的快捷键了

**Comment by xiaoxiunique** [comment]
哈哈，谢谢建议，后面我完善一下。

**Comment by usercao** [comment]
> 已经完善一些 Mac 和 Windows 的对应键位 ，[移步](https://github.com/xiaoxiunique/tool-tips/blob/master/IDEA%20Windows%20Mac%20%E5%BF%AB%E6%8D%B7%E9%94%AE%E5%AF%B9%E6%AF%94.md)
@xiaoxiunique 可以更新一下👍，那个alt+j试了一些时间没找到Mac对应的快捷键

**Comment by usercao** [comment]
@xiaoxiunique 希望文章能在GIF的部分直接对应Win与Mac快捷键的说明👍

**Comment by xiaoxiunique** [comment]
好的 谢谢提醒，后面我补上去  alt + j -> 对应 mac ctrl + G     ctrl + shift + alt + j  对应 Mac ctrl + command + G

**Comment by xiaoxiunique** [comment]
@usercao  已补充

**Comment by usercao** [comment]
@xiaoxiunique 没有找到呢，能发一下链接吗？[我在这里看的](https://atips.cn/idea/IDEA%20%E5%A4%9A%E5%85%89%E6%A0%87%E6%93%8D%E4%BD%9C%E9%9B%86%E9%94%A6.html)

**Comment by xiaoxiunique** [comment]
![image](https://user-images.githubusercontent.com/27221739/90357725-8d5ad080-e086-11ea-82a1-9b60df4c0281.png)

**Comment by xiaoxiunique** [comment]
@usercao 看下 就在你的这个页面

![image](https://user-images.githubusercontent.com/27221739/90357738-9a77bf80-e086-11ea-9ae4-77fafbe6b991.png)
